### PR TITLE
fix empty values not saving in checkbox mode

### PR DESCRIPTION
**Pull request by m0n0mind**
When using checkboxes to select user roles and trying to uncheck all roles, new state is not being saved. instead last saved value stays intact...
( fix based on ACF 4's checkbox field create_field() function )

only fixed for ACF4, though

### CODE REVIEW

**Comment by danielpataki** [comment]
Thanks for the help :) I'm closing this without merging because I'm reworking the plugin structure a bit. I'll have an update out in a few hours which will fix this issue. Also, a single hidden empty field with the same name will fix this :)

**Comment by m0n0mind** [comment]
thanks, just saw your update coming in :)

**Comment by m0n0mind** [comment]
just made the update, but values are no longer being saved at all (just tested checkbox mode).
will stay with the modified version for now.

**Comment by danielpataki** [comment]
Ah thanks, sorry, that was a stupid typo on my end. I updated here and in the WordPress repo, should be all better.

**Comment by Diesector** [comment]
Has this update been pushed to the Wordpress plugin or should we update manually from the repo here?

**Comment by danielpataki** [comment]
Hi Kris,

I believe it should all be working just fine now, take a look at the plugin
from WordPress.org, if it isn't working, do let me know!

Daniel

**Pull request closed without merging**
